#!/usr/bin/env bash
# This script displays "Best School" 10 times,
# and on the 9th iteration, it also displays "Hi"

count=0

while [ $count -lt 10 ]
do
	if [ $count -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( count++ ))
	done
