#!/usr/bin/env bash
# This scripts configures an ubuntu server with;
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

# Check if the script is running in Docker
cp /etc/hosts ~/hosts.new #temporary hosts file
# Set localhost to 127.0.0.2
echo "127.0.0.2 localhost" > ~/hosts.new
# Set facebook.com to 8.8.8.8
echo "8.8.8.8  facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
